version: '3.9'
services:
  go-helloworld-db:
    image: 'postgres'
    environment:
      POSTGRES_USER: hello
      POSTGRES_PASSWORD: hello
      POSTGRES_DB: hello
    volumes:
      - go-helloworld-db-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  go-helloworld-db-volume: